language: php

php:
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

services:
  - mongodb

install:
  - echo y | pecl install mongo
  # - php -r "readfile('https://getcomposer.org/installer');" | php
  # - php composer.phar install --no-interaction --dev


before_script: phpenv config-add myconfig.ini
script: phpunit --bootstrap src/Script/seleciona.php teste/script/selecionaTest.php