language: php

php:
  - 5.6

services:
  - mongodb

install:
  - echo y | pecl install mongo

before_script: phpenv config-add myconfig.ini

script: phpunit --bootstrap src/Script/seleciona.php teste/script/selecionaTest.php